name: Build Library

on:
  push:
    branches:
      - master
      - 'dev/*'
  pull_request:
    branches:
      - master
      - 'dev/*'

jobs:
  build:
    strategy:
      matrix:
        ort_version: [v1.19.0]
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variable based on OS
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "OS_PLATFORM=linux" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "OS_PLATFORM=osx" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "OS_PLATFORM=win" >> $GITHUB_ENV
          fi

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'microsoft/onnxruntime'
          tag: ${{ matrix.ort_version }}
          fileName: 'onnxruntime-${{ env.OS_PLATFORM }}-${{ matrix.architecture }}-${{ matrix.ort_version }}'
          out-file-path: 'libs'
          extract: true

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential cmake
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            brew install cmake
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          fi

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: make -C build

      - name: Install
        run: make -C build install


  
        


